### ISSUE TITLE
Error running code.

### ISSUE THREAD

**Issue by usalexsantos** [Joker316701882/Salient-Object-Detection#20]
When I tried running this code I got this error.

D:\Salient_Object_Detection>python inference.py --rgb_folder=./test
Traceback (most recent call last):
  File "inference.py", line 65, in <module>
    main(parse_arguments(sys.argv[1:]))
  File "inference.py", line 19, in main
    gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction = args.gpu_fraction)
AttributeError: module 'tensorflow' has no attribute 'GPUOptions'

Can you help me?

**Comment by hiSyukri** [comment]
> When I tried running this code I got this error.
> 
> D:\Salient_Object_Detection>python inference.py --rgb_folder=./test Traceback (most recent call last): File "inference.py", line 65, in main(parse_arguments(sys.argv[1:])) File "inference.py", line 19, in main gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction = args.gpu_fraction) AttributeError: module 'tensorflow' has no attribute 'GPUOptions'
> 
> Can you help me?

Hi.. have you solved this?
